### ISSUE TITLE
210412 회의

### ISSUE THREAD

**Issue by gywnd2** [hongyaho/Payroll_system#6]
오늘 회의 내용 팀별로 코멘트 달아주시면 됩니다.

**Comment by gywnd2** [comment]
> 출퇴근기록관리팀


 : User Story 마무리 후 주말까지 User Case 작성하기
@hayeooo

**Comment by hongyaho** [comment]
> 출퇴근 인증팀 

User Story 최종 수정 후 merge
4/18(일)까지 User Case model 작성
@KimJoonOh
