### ISSUE TITLE
Pull request 관련

### ISSUE THREAD

**Issue by hongyaho** [hongyaho/Payroll_system#8]
@KimJoonOh 
제가 잘못해서 풀리퀘 안 하고 그냥 머지해버렸는데,,
수정해서 그냥 마스터로 머지하겠습니다!
다음부턴 더 주의할게요 죄송합니닷,,

FR1. 직원으로서 앱을 실행하면 아이디와 비밀번호를 입력해 로그인 할 수 있다.
FR2. 직원으로서 로그인시 얼굴사진을 찍을 수 있다
FR3. 직원으로서 로그인시 촬영한 얼굴사진을 확인 후 재 촬영할 수 있다.
FR4. 직원으로서 로그인시 얼굴사진을 선택하면 gps 위치정보를 얻을 수 있다.
FR5. 직원으로서 선택한 얼굴사진과 gps 정보를 시스템으로 보내 출근인증을 할 수 있다.
FR6. 직원으로서 로그인 중에는 현재 내 위치좌표를 확인 할 수 있다.
FR7. 직원으로서 로그인 중에는 위치좌표를 시스템으로 5분마다 자동전송 할 수 있다.
FR8. 직원으로서 로그인 중에는 로그아웃버튼을 눌러 로그아웃을 진행 할 수 있다.
FR9. 직원으로서 로그아웃시 얼굴사진을 찍을 수 있다.
FR10. 직원으로서 로그아웃시 촬영한 얼굴사진을 확인 후 재 촬영할 수 있다.
FR11. 직원으로서 로그아웃시 얼굴사진을 선택하면 gps 위치정보를 얻을 수 있다.
FR12. 직원으로서 선택한 얼굴사진과 gps 정보를 시스템으로 보내 퇴근인증을 할 수 있다.
NFR1. 이 시스템은 간편한 조작법으로 처음 쓰는 직원도 쉽게 사용법을 알 수 있다.
NFR2. 이 시스템은 어느곳에서나 실행 할 수 있다.
NFR3. 이 시스템은 짧은 프로세스로 빠르게 출퇴근 인증을 완료할 수 있다.

**Comment by KimJoonOh** [comment]
앗 아녜요!! 그럴수도있져 ㅋㅋ 올려주셔서 감사합니닷!!
